task/0021-CW Multiplication table for number
FRAGMENT-GROUP/improve-skills pull request #104
Opened 2021-07-19 20:30 UTC by Rascass

2021-07-19 20:39 UTC, WhatWasThatt commented
why did you add 3 files in one commit?

2021-07-19 20:45 UTC, WhatWasThatt commented on jest/multiTable/multiTable.test.js
> +});
why don't you have two negative tests?

2021-07-19 21:08 UTC, Rascass commented
> why did you add 3 files in one commit?
fixed

2021-07-19 21:44 UTC, WhatWasThatt approved these changes

2021-07-19 21:44 UTC, WhatWasThatt commented
thanks for your changes. keep up the good work!)

2021-07-20 05:19 UTC, mTeeeur requested changes

2021-07-20 05:19 UTC, mTeeeur commented on tasks/multiTable/multiTable.js
> +  const multiTable = sequence.reduce(tableReducer);
We can split it into one line

2021-07-20 11:02 UTC, WhatWasThatt approved these changes

2021-07-20 14:25 UTC, Rascass commented on tasks/multiTable/multiTable.js
> +  const multiTable = sequence.reduce(tableReducer);
fixed

2021-07-20 18:23 UTC, mTeeeur approved these changes
looks good

2021-07-20 20:07 UTC, WhatWasThatt approved these changes
good job

2021-07-20 22:15 UTC, askomar approved these changes
Ok. But you must name all your commits in correct way. And your file naming must be similar with README

2021-07-20 22:19 UTC, merged