Task/0002 cw do you speak english
FRAGMENT-GROUP/improve-skills pull request #94
Opened 2021-07-19 19:21 UTC by skripchenkoVeta

2021-07-19 19:38 UTC, mTeeeur commented
Why do you want to merge into master? @skripchenkoVeta

2021-07-19 19:39 UTC, mTeeeur requested changes
Please fix linter issues

2021-07-19 21:36 UTC, Rascass requested changes

2021-07-19 21:36 UTC, Rascass commented on test/0002-CW-do-you-speak-english/Do-you-speak-English.mocha.js
> +    it('should return true',()=>{assert.strictEqual(en("LiaEnGLiShAA"),true)});
why don't you use assert.ok() here?

2021-07-19 22:52 UTC, skripchenkoVeta commented on test/0002-CW-do-you-speak-english/Do-you-speak-English.mocha.js
> +    it('should return true',()=>{assert.strictEqual(en("LiaEnGLiShAA"),true)});
ok, I'll fix it. Thanks

2021-07-20 05:12 UTC, mTeeeur approved these changes
Looks good

2021-07-20 13:46 UTC, Rascass approved these changes
ok

2021-07-20 22:01 UTC, askomar approved these changes
Good

2021-07-20 22:03 UTC, merged