task/cw-0044 Looking for a benefactor
FRAGMENT-GROUP/improve-skills pull request #95
Opened 2021-07-19 19:36 UTC by WhatWasThatt

2021-07-19 20:20 UTC, askomar requested changes

2021-07-19 20:20 UTC, askomar commented on tasks/looking-for-a-benefactor/newAvg.js
> +function newAvg(arr, newavg) {
newavg - what style is it?

2021-07-19 20:34 UTC, askomar submitted a review, later dismissed
Maybe nice, but I recommend Misha to check

2021-07-19 20:38 UTC, KarinaKlevzhits reviewed
It's very good job!!Perfect!

2021-07-19 21:46 UTC, KarinaKlevzhits submitted a review, later dismissed

2021-07-20 05:15 UTC, mTeeeur approved these changes
Looks good

2021-07-20 13:47 UTC, Rascass approved these changes
good

2021-07-20 14:44 UTC, askomar approved these changes
Nice

2021-07-20 14:44 UTC, KarinaKlevzhits approved these changes

2021-07-20 22:04 UTC, merged